### ISSUE TITLE
User credentials

### ISSUE THREAD

**Issue by jgarriga78** [fuyb1992/es_pandas#14]
Can I pass a user and pass to the connection to es?
TXS

**Comment by zhangbk920209** [comment]
Just add username and password when creating object of es_pandas, like

> from es_pandas import es_pandsa
>     es = es_pandas('username:passwd@localhost:9200')

**Comment by zhangbk920209** [comment]
> Can I pass a user and pass to the connection to es?
> TXS

Just add username and password when creating object of es_pandas, like

`from es_pandas import es_pandsa`
`es = es_pandas('username:passwd@localhost:9200')`
