### ISSUE TITLE
为什么第一次写入的时候,  _id  是自己生成的?

### ISSUE THREAD

**Issue by davidli006** [fuyb1992/es_pandas#2]
![image](https://user-images.githubusercontent.com/38975448/68856720-30f40a80-071c-11ea-82c4-d0c13f3682c9.png)
![image](https://user-images.githubusercontent.com/38975448/68856750-3cdfcc80-071c-11ea-99d3-2302bc5d0d5d.png)
第一次,让es随机生成,后面想要更新,怎么根据这个来确定唯一.(每次查出来,再去更新可以,有时候没必要).

**Comment by fuyb1992** [comment]
你的意思是第一次写入的时候_id就写入指定的唯一字段值，以后更新就可以直接操作，不用读出来了再更新？

**Comment by fuyb1992** [comment]
你的问题很好，我正打算周末补充一下readme，当你尝试更新数据时，可以使用`to_es_dev`函数，其中
`key_col`参数就是数据的唯一值对应的列名，这个function会判断是否存在对应的index，如果没有直接新建并写入数据，如果有调用`update_to_es` function，从es中分批次取出数据，检查数据是否变化，如有变化根据查出的_id进行更新操作，没有变化的数据不进行任何处理，新增的数据进行写入操作。
