### ISSUE TITLE
Version check fails using SNAPSHOT

### ISSUE THREAD

**Issue by oskrdt** [fuyb1992/es_pandas#22]
The version of my elasticsearch instance ends with `SNAPSHOT` and that's causing to fail when trying to init. 
Version:
```
7.9.1-SNAPSHOT
```
Error I'm getting
```
ValueError: invalid literal for int() with base 10: ‘1-SNAPSHOT’
```

**Comment by fuyb1992** [comment]
Thanks for notifying us of this, it's been fixed in commit: https://github.com/fuyb1992/es_pandas/commit/5d2deb9ca14907ce2984816c0b5722acc1f29dc9. And thanks @sethmlarson for providing ideas.
