### ISSUE TITLE
Something wrong when you run template code

### ISSUE THREAD

**Issue by christopherli86** [fuyb1992/es_pandas#26]
I just pip install `es_pandas`, and attach other packages including progressbar2 (>3),  but can't work.

The following error message:
`Incorrect version of progerssbar package, please do pip install progressbar2`
but the version python detect is the `python_utils` package, then I fixed out, the following error outputs 
`TypeError: __init__() got an unexpected keyword argument 'max_value'`

**Comment by fuyb1992** [comment]
progressbar2(https://pypi.org/project/progressbar2/)和progressbar(https://pypi.org/project/progressbar/)是两个不同的包，有可能你同时安装了这两个包，导致import时导入了错误的包。

**Comment by christopherli86** [comment]
yes, I do the correct package. but  the following error outputs
`TypeError: __init__() got an unexpected keyword argument 'max_value'`

**Comment by fuyb1992** [comment]
请至少提供系统信息，python版本，pip list，es版本，执行语句，和完整报错信息，以便定位
