### ISSUE TITLE
to_pandas sql error

### ISSUE THREAD

**Issue by robomotic** [fuyb1992/es_pandas#28]
Hi there,
I am doing a very simple sql query like this:
```
from elasticsearch import Elasticsearch
from elasticsearch.helpers import bulk
from elasticsearch.helpers.errors import BulkIndexError
import time
import pandas as pd
from es_pandas import es_pandas


import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# crete es_pandas instance
es = es_pandas(es_url,verify_certs=False,ssl_show_warn=False)
```

`es.to_pandas(index='priam_unified_host-2021-05-03', query_sql='select top 10 * from day-2021-05-03 WHERE EventID=4688')`

I get this error:

`TypeError: search() got an unexpected keyword argument 'query_sql'`

**Comment by oskrdt** [comment]
Hi @robomotic , the error that you are getting seems to point that you are using a version of the library that doesn't have the `query_sql` implemented yet. 
I don't see any recent release of the library that includes the latest changes in case that you are using the PIP install process.
@fuyb1992 Should we create a new release to include the latest changes?

**Comment by robomotic** [comment]
Hi there,
thanks for responding.
The version installed via pip:

```
Name: es-pandas
Version: 0.0.20
Summary: Read, write and update large scale pandas DataFrame with ElasticSearch
Home-page: https://github.com/fuyb1992/es_pandas
Author: Frank
Author-email: fu.frank@foxmail.com
License: UNKNOWN
Location: /home/jovyan/.local/lib/python3.8/site-packages
Requires: 
Required-by: 
```

**Comment by robomotic** [comment]
When I install from master (via git clone and before that uninstall).

```
Name: es-pandas
Version: 0.0.20
Summary: Read, write and update large scale pandas DataFrame with ElasticSearch
Home-page: https://github.com/fuyb1992/es_pandas
Author: Frank
Author-email: fu.frank@foxmail.com
License: UNKNOWN
Location: /home/jovyan/work/es_pandas/es_pandas
Requires: 
Required-by: 
```

**Comment by robomotic** [comment]
But despite the version being identical it does have a few changes, it now fails on:

`--> 104             dsl_from_sql = self.es.sql.translate({'query': query_sql})`

which was mentioned to be a bug as in the other issue.

Okay so I guess I will always install from master via git clone.
You can close the issue if you like.
