### ISSUE TITLE
sql_query fetch size

### ISSUE THREAD

**Issue by robomotic** [fuyb1992/es_pandas#29]
Hi there,
what parameter should I pass to provide the fetch size:

https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-translate.html

```
POST /_sql/translate
{
  "query": "SELECT * FROM library ORDER BY page_count DESC",
  "fetch_size": 10
}
```

**Comment by fuyb1992** [comment]
There is a flaw in line 104 of `es_pandas/es_pandas.py,`  ` dsl_from_sql = self.es.sql.translate({'query': query_sql})`, chang it to  ` dsl_from_sql = self.es.sql.translate(query_sql)` may works

**Comment by robomotic** [comment]
Okay I am going to fork and try the fix!

**Comment by oskrdt** [comment]
From PR adding the `query_sql` #27 , there is no current support on `to_pandas` function for limiting the documents retuned neither from DSL or SQL
> Limit/size. No limit available on the function, all matches are returned.

If you have a proposal for adding such feature it would be great.

**Comment by robomotic** [comment]
So here is the problem-o, the dsl translate is confusing to me.
I fixed the code like so:

```
    def to_pandas(self, index, query_rule=None, heads=[], dtype={}, infer_dtype=False, show_progress=True, query_sql=None, **kwargs):
        """
        scroll datas from es, and convert to dataframe, the index of dataframe is from es index,
        about 2 million records/min
        Args:
            index: full name of es indices
            query_rule: dict, default match_all, elasticsearch query DSL
            heads: certain columns get from es fields, [] for all fields
            dtype: dict like, pandas dtypes for certain columns
            infer_dtype: bool, default False, if true, get dtype from es template
            show_progress: bool, default True, if true, show progressbar on console
            query_sql: string, default None, SQL containing query to filter
        Returns:
            DataFrame
        """
        if query_sql:
            query_body = {'query':query_sql}
            if 'fetch_size' in kwargs:
                query_body['fetch_size']=kwargs['fetch_size']
  
            dsl_from_sql = self.es.sql.translate(query_body)
            print(dsl_from_sql)
            if query_rule:
                raise Exception('Cannot use query_rule and query_sql at the same time')
            else:
                query_rule = {'query': dsl_from_sql}
        elif not query_rule:
            query_rule = {'query': {'match_all': {}}}
        count = self.es.count(index=index, body=query_rule)['count']
        if count < 1:
            raise Exception('Empty for %s' % index)
        query_rule['_source'] = heads
        anl = helpers.scan(self.es, query=query_rule, index=index, **kwargs)
        df = pd.DataFrame(self.get_source(anl, show_progress=show_progress, count=count)).set_index('_id')
        if infer_dtype:
            dtype = self.infer_dtype(index, df.columns.values)
        if len(dtype):
            df = df.astype(dtype)
        return df
```

The DSL translated syntax does not resemble a standard elastic query.
In my example:

`{'size': 1000, '_source': False, 'fields': [{'field': '@timestamp', 'format': 'strict_date_optional_time_nanos'}, {'field': 'AuthenticationPackage'}, {'field': 'Destination'}, {'field': 'DomainName'}, {'field': 'EventID'}, {'field': 'FailureReason'}, {'field': 'LogHost'}, {'field': 'LogonID'}, {'field': 'LogonType'}, {'field': 'LogonTypeDescription'}, {'field': 'ParentProcessID'}, {'field': 'ParentProcessName'}, {'field': 'ProcessID'}, {'field': 'ProcessName'}, {'field': 'ServiceName'}, {'field': 'Source'}, {'field': 'Status'}, {'field': 'SubjectDomainName'}, {'field': 'SubjectLogonID'}, {'field': 'SubjectUserName'}, {'field': 'Time'}, {'field': 'UserName'}, {'field': 'event.category'}, {'field': 'host.name'}, {'field': 'message'}, {'field': 'user.name'}], 'sort': [{'_doc': {'order': 'asc'}}]}`

I am not sure how we are supposed to be using that generated object.
The documentation does not say it!

**Comment by robomotic** [comment]
This is intriguing if I change my SQL query with a WHERE condition like so:

`es.to_pandas(index='priam_unified_host-2021-05-03', query_sql="SELECT * FROM \"priam_unified_host-2021-05-03\" WHERE LogonID=4625")`



The query parameter appear:

`{'size': 1000, 'query': {'term': {'LogonID.keyword': {'value': 4625, 'boost': 1.0}}}, '_source': False, 'fields': [{'field': '@timestamp', 'format': 'strict_date_optional_time_nanos'}, {'field': 'AuthenticationPackage'}, {'field': 'Destination'}, {'field': 'DomainName'}, {'field': 'EventID'}, {'field': 'FailureReason'}, {'field': 'LogHost'}, {'field': 'LogonID'}, {'field': 'LogonType'}, {'field': 'LogonTypeDescription'}, {'field': 'ParentProcessID'}, {'field': 'ParentProcessName'}, {'field': 'ProcessID'}, {'field': 'ProcessName'}, {'field': 'ServiceName'}, {'field': 'Source'}, {'field': 'Status'}, {'field': 'SubjectDomainName'}, {'field': 'SubjectLogonID'}, {'field': 'SubjectUserName'}, {'field': 'Time'}, {'field': 'UserName'}, {'field': 'event.category'}, {'field': 'host.name'}, {'field': 'message'}, {'field': 'user.name'}], 'sort': [{'_doc': {'order': 'asc'}}]}`

however I get this error:

`RequestError: RequestError(400, 'parsing_exception', '[size] query malformed, no start_object after query name')`

**Comment by fuyb1992** [comment]
New version is uploaded 0.0.21, https://pypi.org/project/es-pandas/,  you can upgrade `es_pandas` by `pip`. Parameter `query_sql` is updated, it should by string or dict type,  commit:https://github.com/fuyb1992/es_pandas/commit/95fcdfa35dc669123701c4595e04b2a9de47d8a5

**Comment by robomotic** [comment]
Using your new version.
So we still have two problems.

When you run it without any filter:

`es.to_pandas(index='priam_unified_host-2021-05-04', query_sql="SELECT * FROM \"priam_unified_host-2021-05-04\"")`

It fails because the translation does not contain a query key:

```
/opt/conda/lib/python3.8/site-packages/es_pandas/es_pandas.py in to_pandas(self, index, query_rule, heads, dtype, infer_dtype, show_progress, query_sql, **kwargs)
    111                 raise Exception('Cannot use query_rule and query_sql at the same time')
    112             else:
--> 113                 query_rule = {'query': dsl_from_sql['query']}
    114         elif not query_rule:
    115             query_rule = {'query': {'match_all': {}}}

KeyError: 'query'
```

In my code example I check for it and if is missing, I add the match_all as in the elif line 114.

The second problem I found out is odd, when I query like this:

`es.to_pandas(index='priam_unified_host-2021-05-04', query_sql="SELECT * FROM \"priam_unified_host-2021-05-04\" WHERE EventID=4688 LIMIT 10")`

the progress bar shows that is fetching the entire data before doing the limit operation, I don't know whether this is an issue of the SQL translation engine or a bug ?

**Comment by robomotic** [comment]
I also notice that with the above query we are totally loosing the aggregations.

`es.to_pandas(index='priam_unified_host-2021-05-04', query_sql={'query':"SELECT LogHost.keyword,COUNT(*) FROM \"priam_unified_host-2021-05-04\" WHERE EventID=4688 GROUP BY LogHost.keyword",'fetch_size':10})`

The query_rule is:

`{'query': {'term': {'EventID': {'value': 4688, 'boost': 1.0}}}}`

But the full dsl query is:

`{'size': 0, 'query': {'term': {'EventID': {'value': 4688, 'boost': 1.0}}}, '_source': False, 'aggregations': {'groupby': {'composite': {'size': 10, 'sources': [{'78d5e63c': {'terms': {'field': 'LogHost.keyword', 'missing_bucket': True, 'order': 'asc'}}}]}}}}`

**Comment by fuyb1992** [comment]
`sql translate` is inherited from [elasticsearch-py ](https://elasticsearch-py.readthedocs.io/en/7.10.0/xpack.html?highlight=query%20rule#elasticsearch.client.SqlClient.query), the problems above may cause by es version, es py client version or es bugs, I do not have enough time to dig in，you are welcomed to contribute to `es_pandas` project if you have time and energy.

Currently, the main function of  `es_pandas` package is reading, writing, updating or deleting `pd.DataFrame` with elasticserach, if you want something more related to statistics,  [pandasticsearch](https://github.com/onesuper/pandasticsearch)  may helps.
