### ISSUE TITLE
elasticsearch.exceptions.RequestError: RequestError(400, 'parsing_exception', 'request does not support [_source]')

### ISSUE THREAD

**Issue by dummy74** [fuyb1992/es_pandas#3]
Second call of method to_pandas using the default value for argument query_rule raises exception. The default value of argument query_rule should be None. The value should be internally set to default if the user does not set a query_rule.

**Comment by fuyb1992** [comment]
Thanks for your suggestion,  the default value of argument `query_rule` has been changed to None, [Update es_pandas.py](https://github.com/fuyb1992/es_pandas/commit/099ae0f015858e4592e51bd8890a39d17cbfdd18)
