### ISSUE TITLE
在to_pandas函数中，set_index应该在设置dtype以后，否则通过dtype重置'_id'类型会失败

### ISSUE THREAD

**Issue by shuguangbo** [fuyb1992/es_pandas#31]
df = pd.DataFrame(self.get_source(anl, show_progress=show_progress, count=count)).set_index('_id')
        if infer_dtype:
            dtype = self.infer_dtype(index, df.columns.values)
        if len(dtype):
            df = df.astype(dtype)
        return df
-------
        df = pd.DataFrame(self.get_source(anl, show_progress=show_progress, count=count))
        if infer_dtype:
            dtype = self.infer_dtype(index, df.columns.values)
        if len(dtype):
            df = df.astype(dtype)
        df = df.set_index('_id')   <<< 返回之前set_index
        return df

**Comment by fuyb1992** [comment]
从es中获取的_id字段数据格式是什么样的？请举例说明

**Comment by shuguangbo** [comment]
不好意思，忘记说此问题的另一个前提条件 - 没有设置infer_dtype；这时从ES取出数据转换为DataFrame后，默认会设置字段类型为string， 假如'_id'类型为integer, 通过dtype去将'_id'转换为integer则会失败。正确做法是先做类型转换，再设置索引。
