### ISSUE TITLE
Any ways to force push all columns as string? 

### ISSUE THREAD

**Issue by fuad00** [fuyb1992/es_pandas#35]
While importing, pandas makes phone numbers **float**, so converting to **string** adds `.0` at the end.
I decided to check `.0` at the every line and erase it if exists, but now importing is 100x slower
<img width="424" alt="CleanShot 2023-02-14 at 09 02 41@2x" src="https://user-images.githubusercontent.com/26776550/218652813-e26a450f-1674-4c03-976d-35928581c75c.png">

**Comment by fuyb1992** [comment]
Is this issue  related to es_pandas? Please provide more information

**Comment by fuad00** [comment]
> Is this issue related to es_pandas? Please provide more information

question is: can you help to make es_pandas force push columns as strings to es without speed lose?

**Comment by fuyb1992** [comment]
conver dataframe to string dtype, then write to es
