### ISSUE TITLE
0.0.23 error: TypeError: BarNothing.update() missing 1 required positional argument: 'arg'

### ISSUE THREAD

**Issue by virtustate** [fuyb1992/es_pandas#40]
Getting this error with multiple different processes (DataFrames) on Version 0.0.23. No error using Version 0.0.22.

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/algorithm_library/es_servers.py:131, in ESServers.es_pandas_load(self, df, index_name, system)
    129 self.create_es_index(index_name, system)
    130 try:
--> 131     return ep_server.to_es(df, index_name, use_index=True, show_progress=False,
    132                            thread_count=self.es_load_threads, chunk_size=self.es_load_chunk)
    133 except Exception as e:
    134     if system in self.es_server_list_ignore_load_error:
File /databricks/python/lib/python3.10/site-packages/es_pandas/es_pandas.py:52, in es_pandas.to_es(self, df, index, doc_type, use_index, show_progress, success_threshold, _op_type, use_pandas_json, date_format, **kwargs)
     45     doc_type = index + '_type'
     46 gen = helpers.parallel_bulk(self.es,
     47                             (self.rec_to_actions(df, index, doc_type=doc_type, show_progress=show_progress,
     48                                                  use_index=use_index, _op_type=_op_type,
     49                                                  use_pandas_json=use_pandas_json, date_format=date_format)),
     50                             **kwargs)
---> 52 success_num = np.sum([res[0] for res in gen])
     53 rec_num = len(df)
     54 fail_num = rec_num - success_num
File /databricks/python/lib/python3.10/site-packages/es_pandas/es_pandas.py:52, in <listcomp>(.0)
     45     doc_type = index + '_type'
     46 gen = helpers.parallel_bulk(self.es,
     47                             (self.rec_to_actions(df, index, doc_type=doc_type, show_progress=show_progress,
     48                                                  use_index=use_index, _op_type=_op_type,
     49                                                  use_pandas_json=use_pandas_json, date_format=date_format)),
     50                             **kwargs)
---> 52 success_num = np.sum([res[0] for res in gen])
     53 rec_num = len(df)
     54 fail_num = rec_num - success_num
File /databricks/python/lib/python3.10/site-packages/elasticsearch/helpers/actions.py:472, in parallel_bulk(client, actions, thread_count, chunk_size, max_chunk_bytes, queue_size, expand_action_callback, ignore_status, *args, **kwargs)
    469 pool = BlockingPool(thread_count)
    471 try:
--> 472     for result in pool.imap(
    473         lambda bulk_chunk: list(
    474             _process_bulk_chunk(
    475                 client,
    476                 bulk_chunk[1],
    477                 bulk_chunk[0],
    478                 ignore_status=ignore_status,
    479                 *args,
    480                 **kwargs
    481             )
    482         ),
    483         _chunk_actions(
    484             actions, chunk_size, max_chunk_bytes, client.transport.serializer
    485         ),
    486     ):
    487         for item in result:
    488             yield item
File /usr/lib/python3.10/multiprocessing/pool.py:873, in IMapIterator.next(self, timeout)
    871 if success:
    872     return value
--> 873 raise value
File /usr/lib/python3.10/multiprocessing/pool.py:125, in worker(inqueue, outqueue, initializer, initargs, maxtasks, wrap_exception)
    123 job, i, func, args, kwds = task
    124 try:
--> 125     result = (True, func(*args, **kwds))
    126 except Exception as e:
    127     if wrap_exception and func is not _helper_reraises_exception:
File /usr/lib/python3.10/multiprocessing/pool.py:144, in _helper_reraises_exception(ex)
    142 def _helper_reraises_exception(ex):
    143     'Pickle-able helper function for use by _guarded_task_generation.'
--> 144     raise ex
File /usr/lib/python3.10/multiprocessing/pool.py:391, in Pool._guarded_task_generation(self, result_job, func, iterable)
    389 try:
    390     i = -1
--> 391     for i, x in enumerate(iterable):
    392         yield (result_job, i, func, (x,), {})
    393 except Exception as e:
File /databricks/python/lib/python3.10/site-packages/elasticsearch/helpers/actions.py:155, in _chunk_actions(actions, chunk_size, max_chunk_bytes, serializer)
    148 """
    149 Split actions into chunks by number or size, serialize them into strings in
    150 the process.
    151 """
    152 chunker = _ActionChunker(
    153     chunk_size=chunk_size, max_chunk_bytes=max_chunk_bytes, serializer=serializer
    154 )
--> 155 for action, data in actions:
    156     ret = chunker.feed(action, data)
    157     if ret:
File /databricks/python/lib/python3.10/site-packages/es_pandas/es_pandas.py:152, in es_pandas.rec_to_actions(self, df, index, doc_type, use_index, _op_type, use_pandas_json, date_format, show_progress)
    150 if use_index and (_op_type in ['create', 'index']):
    151     for i, row in enumerate(df.itertuples(name=None, index=use_index)):
--> 152         bar.update()
    153         _id = row[0]
    154         record = self.serialize(row[1:], columns, use_pandas_json, iso_dates)

**Comment by fuyb1992** [comment]
upgrade tqdm will solve this problem

**Comment by virtustate** [comment]
Thanks!
